name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image:
  uuid: ^3.0.7
  intl: ^0.18.1
  flutter_fortune_wheel: ^1.3.0
  ticket_widget: ^0.0.1
  google_fonts: ^5.1.0
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true