// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyWySeRQkuhdGUknlObNCUdlaxksVbwFI',
    appId: '1:411721181032:web:3023f8e514c60a1b93d8dd',
    messagingSenderId: '411721181032',
    projectId: 'crudogreniyorum',
    authDomain: 'crudogreniyorum.firebaseapp.com',
    storageBucket: 'crudogreniyorum.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBon0nI2SamL_hZd-pbelip9xANX379bQ4',
    appId: '1:411721181032:android:87a30e7c743a3c6693d8dd',
    messagingSenderId: '411721181032',
    projectId: 'crudogreniyorum',
    storageBucket: 'crudogreniyorum.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdGkcH0wIJr4QrKo9tXXOMk2aUiGAZSlk',
    appId: '1:411721181032:ios:97ef333b36fc5fd593d8dd',
    messagingSenderId: '411721181032',
    projectId: 'crudogreniyorum',
    storageBucket: 'crudogreniyorum.appspot.com',
    iosClientId: '411721181032-f95h3ln616qtvoiqt706b06jn4r1jlan.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdGkcH0wIJr4QrKo9tXXOMk2aUiGAZSlk',
    appId: '1:411721181032:ios:261ccb2c330af92593d8dd',
    messagingSenderId: '411721181032',
    projectId: 'crudogreniyorum',
    storageBucket: 'crudogreniyorum.appspot.com',
    iosClientId: '411721181032-t8nl91a516fo2l6p33dt1nr4qgjbffb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
